### ISSUE TITLE
Update tooltip to make more accessible

### ISSUE THREAD

**Issue by peter-mouland** [sky-uk/nowtv-react-toolkit#108]
Currently the tooltip has no 'aria' attributes and the tooltip itself is removed and added to the dom on click.  It would be better to change this behaviour. as discussed https://github.com/sky-uk/nowtv-react-toolkit/pull/107

 * `role="tooltip"` on the now-tooltip div
 * `aria-describedby="tip-id"` on the now-tooltip-trigger div
   * This will mean we need an id prop as required
 * To ensure screen-readers know about the div, we would need to ensure that the HTML always exist and that we simply show/hide the div on click
   * we can do this using `aria-hidden="true"` and `aria-hidden="false"` and come cool CSS
```CSS
.now-tooltip[aria-hidden="true"] {display:none;}
.now-tooltip[aria-hidden="false"] {display:block;}
```
